### ISSUE TITLE
404 error when open opening link directly

### ISSUE THREAD

**Issue by viet** [minecraftly/minecraftly.github.io#2]
For some reason, on valid links, Angular can't find what I'm looking for and return the 404.

This works: [https://minecraftly.com/#vote](https://minecraftly.com/#vote)
This doesn't work: [https://minecraftly.com/vote](https://minecraftly.com/vote)

**Comment by luongvm** [comment]
because this mode require special config, usually done with rw module on nginx or apache, read more: https://ngmilk.rocks/2015/03/09/angularjs-html5-mode-or-pretty-urls-on-apache-using-htaccess/

**Comment by viet** [comment]
Welp, maybe we need to move this whole static web to Google App Engine and enable mod rewrite hmm. Will think abt this later.

**Comment by viet** [comment]
Fixed without changing host ;3
